name: website

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  website:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.40"
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Build mdBook
        run: |
          mdbook build
        working-directory: ./example
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./example/book/"
      - name: Deploy artifact to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
