name: website

on:
  workflow_dispatch:

jobs:
  website:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.40"

      - name: Install Catppuccin CSS
        run: |
          gh release download v3.0.1 --pattern '*.css' --dir ./example/theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build mdBook
        run: |
          mdbook build
        working-directory: ./example

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./example/book/"

      - name: Deploy artifact to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
